POST http://localhost:9000/api/pin/set
Content-Type: application/json

{  
    "email": "demo@neurowallet.test",
    "pin": "123456"
}

###


POST http://localhost:9000/api/pin/login
Content-Type: application/json

{  
    "email": "demo@neurowallet.com",
    "pin": "123456"
}


###



POST http://localhost:9000/api/pin/login

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGIxMGQxNTk5NTQ0OGQ0Y2RkMjkxMjciLCJlbWFpbCI6ImRlbW9AbmV1cm93YWxsZXQuY29tIiwicmVjZW50QXV0aEF0IjoiMjAyNS0wOC0yOVQwMjoyMToxNC4zNTRaIiwiaWF0IjoxNzU2NDM0MDc0LCJleHAiOjE3NTY0MzU4NzR9.8secl6emBz4jwjZWzjLVQ4YmVG8e2UlJf66v5Pig8VI
Content-Type: application/json
Idempotency-Key: transfer-001

{
    "fromAccountId": "68b10d15995448d4cdd29127",
    "toAccountNumber": "1002003012", 
    "amount": "2000", 
    "memo": "Food"
}





